routes/web.php
<?php

use App\Models\Midtran;
use App\Models\Websystem;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;

use App\Http\Controllers\UserController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\IsolirController;
use App\Http\Controllers\PacketController;
use App\Http\Controllers\RouterController;
use App\Http\Controllers\ServerController;
use App\Http\Controllers\UpdateController;
use App\Http\Controllers\BillingController;
use App\Http\Controllers\InstallController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AutoIsolirController;
use App\Http\Controllers\TestCommandController;
use App\Http\Controllers\Midtran\OrderController;
use App\Http\Controllers\TestConnectionController;
use App\Http\Controllers\Mikrotik\SystemController;
use App\Http\Controllers\Customer\PaymentController;
use App\Http\Controllers\Mikrotik\MikrotikController;
use App\Http\Controllers\Auth\CustomerLoginController;
use App\Http\Controllers\Mikrotik\Ppp\SecretController;
use App\Http\Controllers\PaymentGateway\MidtranController;
use App\Http\Controllers\Midtran\PaymentCallbackController;
use App\Http\Controllers\PaymentGateway\PaymentGatewayController;
use App\Http\Controllers\Customer\ProfileController as CustomerProfileController;
use App\Http\Controllers\Mikrotik\Ppp\ProfileController as MikrotikProfileController;
use App\Http\Controllers\WebsystemController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/




//Silahkan dihapus setelah melakukan instalasi
// Route::get('install', [InstallController::class, 'install'])->name('install');
// Route::get('install/start', [InstallController::class, 'start'])->name('installStart');
// Route::get('install/create', [InstallController::class, 'create_admin'])->name('installCreateAdmin');
// Route::post('install/store', [InstallController::class, 'store_admin'])->name('installStoreAdmin');
// Route::get('install/finish', [InstallController::class, 'finish'])->name('installFinish');
//Batas akhir hapus setelah instalasi


Route::get('/isolir', [IsolirController::class, 'index'])->name('isolir');
Route::redirect('/', '/customer/login');
Route::post('payments/midtrans-notification', [PaymentCallbackController::class, 'receive']);
Route::get('/customer/register', [CustomerLoginController::class, 'register'])->name('customer.register');
Route::post('/customer/register', [CustomerLoginController::class, 'store'])->name('customer.add');

Route::group(['prefix' => 'customer', 'namespace' => 'Customer'], function () {
    Route::group(['middleware' => 'guest'], function () {
        Route::get('/login', [CustomerLoginController::class, 'login'])->name('customerLogin');
        Route::post('/login', [CustomerLoginController::class, 'postLogin'])->name('customerLoginPost');
    });
    Route::group(['middleware' => 'customerauth'], function () {
        Route::get('/', [CustomerProfileController::class, 'index'])->name('customer.dashboard');
        Route::get('/profile', [CustomerProfileController::class, 'show'])->name('customer.profile');
        Route::post('/logout', [CustomerLoginController::class, 'customerLogout'])->name('customerLogout');
        Route::get('billings/payments', [PaymentController::class, 'index'])->name('customer.payment.index');
        Route::get('billings/payments/{status}/show', [PaymentController::class, 'index'])->name('customer.payment.state');
        Route::get('billings/payments/{billing:id}/view', [PaymentController::class, 'show'])->name('customer.payment.show');
        Route::get('billings/orders', [OrderController::class, 'index'])->name('customer.order.index');
        Route::get('billings/orders/{status}/show', [OrderController::class, 'index'])->name('customer.order.state');
        Route::get('billings/orders/{order:id}/view', [OrderController::class, 'show'])->name('customer.order.show');
        Route::post('billings/orders/{order:id}/update', [OrderController::class, 'update'])->name('customerOrder.update');
        Route::get('billings/orders/{billing:id}/create', [OrderController::class, 'create'])->name('customer.order.create');
        Route::post('/payment/success', [OrderController::class, 'paymentSuccess'])->name('payment.success');
        Route::post('/customer/activation/{customer}', [CustomerController::class, 'activations'])->name('customer.activations');


        //  }
    });
});
Route::group(['prefix' => 'admin'], function () {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]);
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/home', HomeController::class)->name('home');
        Route::view('about', 'about')->name('about');
        Route::get('profile', [ProfileController::class, 'show'])->name('profile.show');
        Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
        Route::post('/testcon', [TestConnectionController::class, 'testConn'])->name('test-con');
        Route::post('server/cek-online', [TestConnectionController::class, 'checkOnline'])->name('check-online');
        Route::get('/server/{mikrotik:slug}', [MikrotikController::class, 'show'])->name('mikrotiks.show');
        Route::resource('test-command', TestCommandController::class);
        Route::get('/server/{mikrotik:slug}/get-resource', [SystemController::class, 'routerResource'])->name('mikrotik.resources');
        Route::get('/server/{mikrotik:slug}/ppp/secrets', [SecretController::class, 'index'])->name('ppp.secrets.index');
        Route::get('/server/{mikrotik:slug}/ppp/secret/create', [SecretController::class, 'create'])->name('ppp.secret.create');
        Route::post('/server/{mikrotik:slug}/ppp/secret/store', [SecretController::class, 'store'])->name('ppp.secret.store');
        Route::put('/server/{mikrotik:slug}/ppp/secret/update', [SecretController::class, 'update'])->name('ppp.secret.update');
        Route::post('/server/{mikrotik:slug}/ppp/secret/import', [SecretController::class, 'clone_secret'])->name('ppp.secret.clone');
        Route::put('/server/{mikrotik:slug}/ppp/secret/enable', [SecretController::class, 'enable'])->name('ppp.secret.enable');
        Route::put('/server/{mikrotik:slug}/ppp/secret/disable', [SecretController::class, 'disable'])->name('ppp.secret.disable');
        Route::get('/server/{mikrotik:slug}/ppp/secret/edit', [SecretController::class, 'edit'])->name('ppp.secret.edit');
        Route::delete('/server/{mikrotik:slug}/ppp/secret/delete', [SecretController::class, 'delete'])->name('ppp.secret.delete');
        Route::get('/server/{mikrotik:slug}/ppp/profiles', [MikrotikProfileController::class, 'index'])->name('ppp.profiles.index');
        Route::post('/server/{mikrotik:slug}/ppp/profiles/import', [MikrotikProfileController::class, 'clone_profile'])->name('ppp.profiles.clone');
        Route::resource('packets', PacketController::class);
        Route::get('/packets/{packet:slug}/delete', [PacketController::class, 'delete'])->name('paket.delete');
        Route::put('/packets/{packet:slug}/disabled/true', [PacketController::class, 'disable'])->name('paket.disable');
        Route::put('/packets/{packet:slug}/disabled/false', [PacketController::class, 'enable'])->name('paket.enable');
        Route::resource('customers', CustomerController::class);
        Route::get('/customers/search', [PaymentController::class, 'index'])->name('customers.search');
        Route::put('/customers/{customer:slug}/disabled/true', [CustomerController::class, 'disable'])->name('customers.disable');
        Route::put('/customers/{customer:slug}/disabled/false', [CustomerController::class, 'enable'])->name('customers.enable');
        Route::put('/customers/{customer:slug}/force-disabled/true', [CustomerController::class, 'forceDisable'])->name('customers.forceDisable');
        Route::put('/customers/{customer:slug}/force-disabled/false', [CustomerController::class, 'forceEnable'])->name('customers.forceEnable');
        Route::get('/customers/offline/show', [CustomerController::class, 'showCustomerOffline'])->name('customers.show.offline');
        Route::get('/customers/{customer:slug}/delete', [CustomerController::class, 'delete'])->name('customers.delete');
        Route::get('/customers/{customer:slug}/edit/ppp', [CustomerController::class, 'editPpp'])->name('customers.edit.ppp');
        Route::patch('/customers/{customer:slug}/ppp/update', [CustomerController::class, 'updatePpp'])->name('customers.update.ppp');
        Route::get('/customers/{customer:slug}/router/edit', [CustomerController::class, 'editRouter'])->name('customers.edit.router');
        Route::patch('/customers/{customer:slug}/router/update', [CustomerController::class, 'updateRouter'])->name('customers.update.router');
        Route::put('/customers/{customer:slug}/activation', [CustomerController::class, 'activation'])->name('customers.activation');
        Route::put('/customers/{customer:slug}/activations', [CustomerController::class, 'activations'])->name('customers.activation');
        Route::delete('billing/periode/{billingperiode:id}/destroy', [BillingController::class, 'destroyPeriode'])->name('billing.periode.destroy');
        Route::get('billing/periode/{billingperiode:id}/delete', [BillingController::class, 'deletePeriode'])->name('billing.periode.delete');
        Route::resource('billings', BillingController::class);

app/Models/Billing/Billing.php
<?php

namespace App\Models\Billing;

use App\Models\Order;
use App\Models\Customer;
use App\Models\Billing\BillingPeriode;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Billing extends Model
{
    use HasFactory;
    public $guarded = [];

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function customer(): BelongsTo
    {
        return $this->belongsTo(Customer::class);
    }


    public function billing_periode(): BelongsTo
    {
        return $this->belongsTo(BillingPeriode::class);
    }
    /**
     * Get all of the comments for the Billing
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function orders(): HasMany
    {
        return $this->hasMany(Order::class);
    }
}

app/Models/Billing/BillingPeriode.php
<?php

namespace App\Models\Billing;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BillingPeriode extends Model
{
    use HasFactory;
    public $guarded = [];
}

app/View/Components/Layouts/Cpanel/Billings/AppLayout.php
<?php

namespace App\View\Components\Layouts\Cpanel\Billings;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Create a new component instance.
     */
    public mixed $title;
    public function __construct($title = 'Customer Management')
    {
        $this->title = $title;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.layouts.cpanel.billings.app-layout');
    }
}

app/View/Components/Layouts/Cpanel/Billings/Navigation.php
<?php

namespace App\View\Components\Layouts\Cpanel\Billings;

use Closure;
use App\Models\Customer;
use Illuminate\View\Component;
use App\Models\Billing\Billing;
use Illuminate\Contracts\View\View;

class Navigation extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        $customers = Customer::orderBy('address', 'ASC')->where('address', '!=', NULL)->get();
        $addressUnique = $customers->unique('address');
        $address = $addressUnique->pluck('address', 'address');
        $years = Billing::orderBy('year', 'DESC')->pluck('year', 'year');
        // $months = Billing::orderBy('month', 'DESC')->pluck('month', 'month');
        return view('components.layouts.cpanel.billings.navigation', compact('years', 'address'));
    }
}

resources/views/billings/create.blade.php
<x-layouts.cpanel.billings.app-layout title="{{ __('billing.title.create') }}">

    <div class="card-header py-3">
        <h5 class="m-0 font-weight-bold text-primary">{{ __('billing.header.create') }}</h5>
    </div>

    <div class="row">
        <div class="col-lg-12">

            {!! Form::open(array('route' => 'billings.store','method'=>'POST')) !!}

            <div class="card-body col-lg-8">

                <div class="row align-items-center">
                    <div class="col-md-12 mb-3">
                        <label for="periode"><strong>{{ __('billing.label.periode') }}</strong></label>
                        <div class="input-group">
                            <select name="name" class="form-control">
                                <option value="">{{ __('billing.placeholder.select.periode') }}</option>

                                @foreach($billingPeriodes as $date)
                                <option value="{{ $date->format('F Y') }}" {{ $date->format('F Y') == request()->query('period') ? 'selected' : '' }}>
                                    {{ $date->format('F Y') }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success" id="button-save"><i class="fa fa-save"></i> {{ __('billing.button.save-create') }}</button>
                <a class="btn btn-primary" href="{{ route('billings.index') }}"><i class="fa fa-arrow-left"></i> {{ __('billing.button.cancel') }}</a>
            </div>
            {!! Form::close() !!}
            <div class="card-body">
                <table id="billingsTable" cellspacing="0" width="100%" class="table  datatable-loading no-footer sortable searchable">
                    <tr>
                        <th width="80px">{{ __('billing.table.no') }}</th>
                        <th>{{ __('billing.table.periode') }}</th>
                        <th width="160px">{{ __('billing.table.action') }}</th>
                    </tr>
                    @foreach ($data as $key => $billingPeriode)
                    <tr>
                        <td>{{ ++$i }}</td>

                        <td>{{ $billingPeriode->name }}</td>

                        <td class="d-flex items-center justify-content-end">
                            <a href="{{ route('billing.periode.delete', $billingPeriode->id) }}" class="btn btn-danger btn-sm">
                                <i class="fa fa-trash me-2 text-white"></i>
                                {{ __('billing.button.delete') }}
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</x-layouts.cpanel.billings.app-layout>

resources/views/billings/create_one.blade.php
<x-layouts.cpanel.billings.app-layout title="{{ __('billing.title.create-one') }}">

    <div class="card-header py-3">
        <h5 class="m-0 font-weight-bold text-primary">{{ __('billing.header.create-one') }}</h5>
    </div>

    <div class="row">
        <div class="col-lg-12">
            {!! Form::open(array('route' => 'billings.store.one','method'=>'POST')) !!}
            <div class="card-body col-lg-8">

                <div class="row align-items-center">
                    <div class="col-md-12 mb-3">
                        <label for="periode"><strong>{{ __('billing.label.periode') }}</strong></label>
                        <div class="input-group">
                            <select name="name" class="form-control">
                                <option value="">{{ __('billing.placeholder.select.periode') }}</option>
                                @foreach($periodes as $periode)
                                <option value="{{ $periode->id }}">
                                    {{ $periode->name }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        @if ($errors->has('name'))
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>


                <div class="card-footer">
                    <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> &nbsp {{ __('billing.button.save-add') }}</button>
                    <a class="btn btn-secondary" href="{{ route('billings.index') }}"><i class="fa fa-arrow-left"></i> &nbsp {{ __('billing.button.cancel') }}</a>
                </div>

                {!! Form::close() !!}
            </div>
        </div>
</x-layouts.cpanel.billings.app-layout>

resources/views/billings/delete.blade.php
<x-layouts.cpanel.billings.app-layout title="{{ __('billing.title.delete') }}">

    <div class="card-header py-3 alert-danger">
        <h5 class="m-0 font-weight-bold"> {{ __('billing.header.delete', ['billingperiode' => $billingperiode->name]) }}</h5>
    </div>

    <div class="row">
        <div class="col-lg-12">

            {!! Form::open(['method' => 'DELETE','route' => ['billing.periode.destroy', ['billingperiode' => $billingperiode->id]]]) !!}
            <div class="card-body col-lg-10">
                <div class="col-md-12 mb-3">
                    <div class="alert alert-danger">
                        <strong>{{ __('billing.info.are_you_sure_to_delete_billing', ['billingperiode' => $billingperiode->name]) }}</strong><br><br>
                        {{ __('billing.info.warning-delete', ['billingperiode' => $billingperiode->name]) }}<br>
                        {{ __('billing.info.after-delete') }}<br><br>
                        {{ __('billing.info.press-button', ['button-delete' => 'delete', 'button-cancel'=> 'cancel', 'billingperiode' => $billingperiode->name]) }}
                        <div class="mt-3">
                            @can ('server-delete')
                            <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash me-2"></i>&nbsp{{ __('billing.button.delete') }}</button>
                            @endcan
                            <a class="btn btn-sm btn-secondary" href="{{ route('billings.create') }}"><i class="fa fa-arrow-left"></i>&nbsp{{ __('billing.button.cancel') }}</a>
                        </div>
                    </div>

                </div>
            </div>
            {!! Form::close() !!}
        </div>
</x-layouts.cpanel.billings.app-layout>

resources/views/billings/index.blade.php
<x-layouts.cpanel.billings.app-layout title="Billings">

    <div class="card-header py-3">
        <h5 class="mb-2 font-weight-bold text-primary">{{ __('billing.header.index') }}</h5>
        <span>
            @can('billing-create')
                <a class="btn btn-success btn-sm" href="{{ route('billings.index', ['download' => 'pdf']) }}"
                    target="_blank"><i class="fa fa-print"></i> Cetak PDF</a>
            @endcan
        </span>
        @if (isset($message))
            <div class="alert alert-danger mt-2">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ $message }}
            </div>
        @else
            <div class="alert alert-success mt-2">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ $data->total() }} billings found
            </div>
        @endif
    </div>

    <div class="card-body">
        <div class="table-responsive">
            {{ $data->withQueryString()->links() }}
            @if ($totalPrice > 0)
                <div class="alert alert-success mt-2">
                    <strong> Total Bill: @moneyIDR($totalPrice) </strong>
                </div>
            @endif
            <table id="billingsTable" cellspacing="0" width="100%"
                class="table  datatable-loading no-footer sortable searchable">
                <tr>
                    <th>{{ __('billing.table.no') }}</th>
                    <th>{{ __('billing.table.customer-name') }}</th>
                    <th>{{ __('billing.table.address') }}</th>
                    <th>{{ __('billing.table.periode') }}</th>
                    <th>{{ __('billing.table.bill') }}</th>
                    <th>{{ __('billing.table.bill-state') }}</th>
                    {{-- <th>{{ __('Status Payments') }}</th> --}}
                    <th class="text-center">{{ __('Action') }}</th>
                </tr>
                @foreach ($data as $key => $billing)
                    <tr>
                        <td><span class="badge text-primary">{{ ++$i }}</span></td>

                        <td><a href="{{ route('billings.show', $billing->slug) }}" data-bs-toggle="tooltip"
                                data-bs-placement="top" title="Show Billing">
                                <span class="badge text-danger">{{ $billing->customer_name ?? 'no name' }}</span></a>
                        </td>
                        <td><span class="badge text-primary">{{ $billing->customer->address ?? 'no address' }}</span>
                        </td>
                        <td><span
                                class="badge text-primary">{{ $billing->billing_periode->name ?? 'no periode' }}</span>
                        </td>
                        <td>
                            <span class="badge bg-blue-soft text-danger">
                                @if ($billing->paket_price === 0)
                                    {{ __('Free') }}
                                @else
                                    @moneyIDR($billing->paket_price)
                                @endif
                            </span>
                        </td>
                        <td>
                            @if ($billing->status === 'LS')
                                <span class="badge bg-success text-white">
                                    <i class="fas fa-check-circle"></i>
                                    {{ __('billing.state.lunas') }}
                                </span>
                            @elseif ($billing->status === 'PL')
                                <span class="badge bg-warning text-white">
                                    <i class="fas fa-ban"></i>
                                    {{ __('billing.state.paylater') }}
                                </span>
                            @else
                                <span class="badge bg-danger text-white">
                                    <i class="fas fa-ban"></i>
                                    {{ __('billing.state.belum-lunas') }}
                                </span>
                            @endif
                        </td>
                        {{-- <td class="text-center"> --}}
                        {{-- @if ($billing->order->payment_status == 2)
                            <span class="badge bg-success text-white">
                                <i class="fas fa-check-circle"></i>
                                {{ __('billing.state.lunas') }}
                            </span>
                        @else
                            <span class="badge bg-danger text-white">
                                <i class="fas fa-ban"></i>
                                {{ __('billing.state.belum-lunas') }}
                            </span>
                        @endif --}}
                        {{-- </td> --}}
                        <td class="d-flex items-center justify-content-end">
                            @can('billing-edit')
                                @if ($billing->status === 'BL' || $billing->status === 'PL')
                                    @if ($billing->customer->activation === 'true')
                                        {!! Form::model($billing, ['method' => 'PATCH', 'route' => ['billings.payment', $billing->slug]]) !!}
                                        <a class="btn btn-success btn-sm"
                                            onclick="event.preventDefault(); this.closest('form').submit();">
                                            <i class="fas fa-money-bill-wave text-white"></i>
                                            {{ __('billing.button.pay') }}
                                        </a>
                                        {!! Form::close() !!}
                                        <a href="{{ route('billings.paylater', $billing->slug) }}"
                                            class="btn btn-success btn-sm ml-1">
                                            <i class="fas fa-money-bill-wave text-white"></i>
                                            {{ __('billing.button.pay-later') }}
                                        </a>
                                    @else
                                        <form method="POST" class="d-inline"
                                            action="{{ route('customers.activation', $billing->customer->slug) }}">
                                            @csrf
                                            @method('put')
                                            <a class="btn btn-success btn-sm"
                                                onclick="event.preventDefault(); this.closest('form').submit();">
                                                <i class="fa fa-check me-2 text-white"></i>
                                                {{ __('billing.button.pay') }}
                                            </a>
                                        </form>
                                    @endif
                                @elseif ($billing->status === 'LS')
                                    {!! Form::model($billing, ['method' => 'PATCH', 'route' => ['billings.unpayment', $billing->slug]]) !!}
                                    <a class="btn btn-danger btn-sm"
                                        onclick="event.preventDefault(); this.closest('form').submit();">
                                        <i class="fas fa-money-bill-wave text-white"></i>
                                        {{ __('billing.button.unpay') }}
                                    </a>
                                    {!! Form::close() !!}
                                @endif
                            @endcan
                        </td>
                    </tr>
                @endforeach
            </table>
            {{ $data->withQueryString()->links() }}
        </div>
    </div>
</x-layouts.cpanel.billings.app-layout>